### ISSUE TITLE
The used permalink is not the pretty URL

### ISSUE THREAD

**Issue by ldidry** [simonfrey/mastodon_wordpress_autopost#23] opened 2018-10-23 06:03 UTC
The toot use URL like `https://framablog.org/?p=14401` instead of pretty URL like `https://framablog.org/2018/10/23/intimite-numerique-le-truc-a-fait-mouche/`.

Example: https://framapiaf.org/@Framasoft/100943356867379054

**Comment by simonfrey** [comment] 2018-10-26 06:41
Should be fixed with 3.2. Please test it and give me feedback if the issue is fixed for you.

Thanks!

**Comment by simonfrey** [comment] 2018-12-11 15:51
As here is no feedback I assume the issue is closed.

**Closed by simonfrey** 2018-12-11 15:51 UTC

**Comment by ldidry** [comment] 2018-12-11 15:58
Ho, sorry, I forgot to answer (or missed the notification). And no, it's still not fixed. We use 3.2.2 and it still not works: https://framapiaf.org/@Framasoft/101215383617139112
I think that our articles are programmed (ie, publish it at XXhXXm on XX/XX/XXXX wordpress feature). It may be the source of the bug, don't you think?

**Comment by simonfrey** [comment] 2018-12-11 17:38
Yes that was it. The future post are now generated differently. 

Should work with 3.2.3
